name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    env:
      CGO_CFLAGS_ALLOW: -Xpreprocessor
      VIPS_VERSION: 8.17.1
      FFMPEG_VERSION: 7.1.1
      V: 5

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.25

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install linux dependencies
        run: |
          # Add backports for updated libheif
          echo "deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/backports.list
          sudo apt-get update
          sudo apt-get install -y \
          meson ninja-build \
          libglib2.0-dev libexpat-dev librsvg2-dev libpng-dev \
          libjpeg-turbo8-dev libimagequant-dev libfftw3-dev \
          libpoppler-glib-dev libxml2-dev \
          libopenslide-dev libcfitsio-dev liborc-0.4-dev libpango1.0-dev \
          libtiff5-dev libgsf-1-dev giflib-tools libwebp-dev \
          yasm libx264-dev libx265-dev libnuma-dev libvpx-dev libtheora-dev  \
          librtmp-dev libvorbis-dev libdav1d-dev libaom-dev \
          libopenjp2-7-dev libcgif-dev
          # Install newer libheif from backports
          sudo apt-get install -y -t jammy-backports libheif-dev || sudo apt-get install -y libheif-dev

      - name: Cache libvips
        uses: actions/cache@v3
        with:
          path: vips-${{ env.VIPS_VERSION }}
          key: ${{ runner.os }}-vips-${{ env.V }}-${{ env.VIPS_VERSION }}
          restore-keys: |
            ${{ runner.os }}-vips-${{ env.V }}-

      - name: Build libvips from source
        run: |
          if [ ! -d "vips-${{ env.VIPS_VERSION }}" ]
          then
            wget https://github.com/libvips/libvips/releases/download/v${{ env.VIPS_VERSION }}/vips-${{ env.VIPS_VERSION }}.tar.xz
            tar xf vips-${{ env.VIPS_VERSION }}.tar.xz
          fi
          cd vips-${{ env.VIPS_VERSION }}
          meson setup _build \
          --buildtype=release \
          --strip \
          --prefix=/usr/local \
          --libdir=lib \
          -Dmagick=disabled \
          -Dintrospection=disabled
          ninja -C _build
          sudo ninja -C _build install
          sudo ldconfig

      - name: Cache ffmpeg
        uses: actions/cache@v3
        with:
          path: ffmpeg-${{ env.FFMPEG_VERSION }}
          key: ${{ runner.os }}-ffmpeg-${{ env.V }}-${{ env.FFMPEG_VERSION }}
          restore-keys: |
            ${{ runner.os }}-ffmpeg-${{ env.V }}-

      - name: Build ffmpeg from source
        run: |
          if [ ! -d "ffmpeg-${{ env.FFMPEG_VERSION }}" ]
          then
            wget https://ffmpeg.org/releases/ffmpeg-${{ env.FFMPEG_VERSION }}.tar.xz
            tar xf ffmpeg-${{ env.FFMPEG_VERSION }}.tar.xz
          fi
          cd ffmpeg-${{ env.FFMPEG_VERSION }}
          ./configure --prefix=/usr/local  \
          --disable-debug  \
          --disable-doc  \
          --disable-ffplay \
          --disable-static  \
          --enable-shared  \
          --enable-version3  \
          --enable-gpl  \
          --enable-libtheora \
          --enable-libvorbis \
          --enable-librtmp \
          --enable-libwebp \
          --enable-libvpx  \
          --enable-libx265  \
          --enable-libx264 \
          --enable-libdav1d \
          --enable-libaom
          make && sudo make install
          sudo ldconfig

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: make get

      - name: Test
        run: make test

      - name: Commit golden files
        if: github.event_name == 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "test: update golden files"
          file_pattern: "testdata/golden"

      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
